networks:
  hermes-net:
    external: true
    name: hermes-net
  lvg:
    driver: bridge
    internal: true
    name: hermes-lvg

volumes:
  hermes-vault-vol:
    name: hermes-vault
  hermes-loki-vol:
    name: hermes-loki
  hermes-grafana-vol:
    name: hermes-grafana
  hermes-prometheus-vol:
    name: hermes-prometheus
  hermes-vault-file-vol:
    name: hermes-vault-file
  hermes-vault-logs-vol:
    name: hermes-vault-logs
  hermes-vector-vol:
    name: hermes-vector

services:
  vector:
    container_name: hermes-vector
    build:
      context: vector
      dockerfile: Dockerfile
      args:
        VECTOR_IMAGE: timberio/vector:0.55.0-debian
    restart: unless-stopped
    volumes:
      - /var/log/journal:/var/log/journal:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - hermes-vector-vol:/var/lib/vector:rw
    user: "0"
    networks:
      - lvg
    depends_on:
      - loki
    mem_limit: 500M
    logging:
      driver: journald

  loki:
    container_name: hermes-loki
    build:
      context: loki
      dockerfile: Dockerfile
      args:
        LOKI_IMAGE: grafana/loki:3.7.2
    restart: unless-stopped
    volumes:
      - hermes-loki-vol:/loki:rw
    networks:
      - lvg
    command: -config.file=/etc/loki/loki-config.yaml
    user: root
    mem_limit: 500M
    logging:
      driver: journald

  grafana:
    container_name: hermes-grafana
    build:
      context: grafana
      dockerfile: Dockerfile
      args:
        GRAFANA_IMAGE: grafana/grafana:13.0.1
    restart: unless-stopped
    env_file:
      - /opt/data/credentials/services.env
    volumes:
      - hermes-grafana-vol:/var/lib/grafana:rw
      - /opt/data/backup/grafana:/opt/data/backup/grafana:rw
      - /tmp/data/grafana:/tmp/data/grafana:rw
    networks:
      - hermes-net
      - lvg
    expose:
      - "3000"
    depends_on:
      - loki
    mem_limit: 500M
    logging:
      driver: journald

  cadvisor:
    image: ghcr.io/google/cadvisor:v0.57.0
    container_name: hermes-cadvisor
    restart: unless-stopped
    privileged: true
    command:
      - "--docker_only"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - hermes-net
    mem_limit: 200M
    logging:
      driver: journald

  prometheus:
    build:
      context: prometheus
      dockerfile: Dockerfile
    container_name: hermes-prometheus
    restart: unless-stopped
    extra_hosts:
      - 'host:host-gateway'
    command:
    user: root
    entrypoint:
      - '/bin/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - hermes-prometheus-vol:/prometheus:rw
    networks:
      - hermes-net
    mem_limit: 500M
    logging:
      driver: journald

  hermes-proxy:
    build:
      context: files
      dockerfile: Dockerfile
    container_name: hermes-proxy
    restart: unless-stopped
    volumes:
      - /:/mnt/host:ro
      - ./files/hermes-proxy-nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - /opt/data/credentials/mm_pat.txt:/etc/nginx/mm_pat.txt:ro
    networks:
      - hermes-net
    expose:
      - "80"
    mem_limit: 200M
    logging:
      driver: journald

  vault:
    image: hashicorp/vault:2.0.2
    container_name: hermes-vault
    restart: unless-stopped
    command: server -config=/vault/config/config.hcl
    user: root
    entrypoint: /vault/config/entrypoint.sh
    volumes:
      - hermes-vault-vol:/vault/data:rw
      - hermes-vault-file-vol:/vault/file:rw
      - hermes-vault-logs-vol:/vault/logs:rw
      - ./vault/config.hcl:/vault/config/config.hcl:ro
      - ./vault/entrypoint.sh:/vault/config/entrypoint.sh:ro
    networks:
      - hermes-net
    cap_add:
      - IPC_LOCK
    mem_limit: 500M
    logging:
      driver: journald
